Vagrant.configure("2") do |config|
  # Box base
  config.vm.box = "ubuntu/jammy64"

  # Nombre de la VM
  config.vm.hostname = "bash-lab"

  # Acceder al puerto 3000 desde el host 8080
  config.vm.network "forwarded_port", guest: 3000, host: 8080

  # Recursos mínimos
  config.vm.provider "virtualbox" do |vb|
    vb.name = "bash-lab"
    vb.memory = 1024
    vb.cpus = 1
  end

  # Provision básico
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y curl git tree
    echo "Entorno listo para practicar bash scripting"
  SHELL
end